# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Utiliser votre fournisseur de base de données pour récupérer les utilisateurs
        my_database_provider:
            entity:
                class: App\Entity\User
                property: email # ou username, selon ce que vous utilisez pour identifier l'utilisateur

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: my_database_provider # Utiliser le fournisseur de base de données
            user_checker: App\Security\UserChecker
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home # Redirection après la connexion réussie
            logout:
                path: app_logout
                target: app_login

    access_control:
    # Définir les règles d'accès en fonction de vos besoins
    # Par exemple:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
